<section>
    <article class="icon_field">
        <ul>
            <li>
                <a class="icon_field_link" href="#especialidades"> <div class="icon_field_icon icon_field_especialidades"></div></a>
            </li>
            <li>
                <a class="icon_field_link" href="#medicos"><div class="icon_field_icon icon_field_medico"></div></a>
            </li>
            <li>
                <a class="icon_field_link" href="#acordos"><div class="icon_field_icon icon_field_acordos"></div></a>
            </li>
            <li>
                <a class="icon_field_link" href="#consulta"><div class="icon_field_icon icon_field_consulta"></div></a>
            </li>
            <li>
                <a class="icon_field_link" href="#contacto"><div class="icon_field_icon icon_field_contacto"></div></a>
            </li>
        </ul>
    </article>
</section>
<section>
    <article class="entry_1">
<!--               <figure class="entry_1_image">
                    <img src="<?php echo ROOT; ?>img/doctor.png" />
                </figure>
                <div class="slider_news">
                    <div>
                        <h2 class="slider_news_title">Rastreio Cancro do Cólon e Recto</h2>
                        <p class="slider_news_text">No próximo mês de Março, a Unidade de Coloproctologia da Clínica 
        da Idade promove um Rastreio gratuito ao cancro do cólon e recto.</p>
                        <a class="slider_news_link" href=""><img src="<?php echo ROOT; ?>img/button.png"/></a>
                        <div class="slider_news_divider"></div>
                         <h2 class="slider_news_title">Nova consulta de enfermagem</h2>
                        <p class="slider_news_text">A Clínica da Idade, disponibiliza aos seus utentes e à população em 
        geral, uma nova consulta gratuita, Consulta de Enfermagem,
        de modo a proporcionar a todos um acompanhamento
        personalizado e especializado.</p>
                        <a class="slider_news_link" href=""><img src="<?php echo ROOT; ?>img/button.png"/></a>
                    </div>
                    <div>         
                        <h2 class="slider_news_title">Terapia da Fala</h2>
                        <p class="slider_news_text">A Clínica da Idade disponibiliza um novo serviço de modo a oferecer aos seus utentes um vasto leque de possibilidades terapêuticas: terapia da fala.</p>
                        <a class="slider_news_link" href=""><img src="<?php echo ROOT; ?>img/button.png"/></a>
                        <div class="slider_news_divider"></div>
                         <h2 class="slider_news_title">Rastreio Cancro do Cólon e Recto</h2>
                        <p class="slider_news_text">No próximo mês de Março, a Unidade de Coloproctologia da Clínica 
        da Idade promove um Rastreio gratuito ao cancro do cólon e recto.</p>
                        <a class="slider_news_link" href=""><img src="<?php echo ROOT; ?>img/button.png"/></a>
                    </div>
        
        
                </div>-->

<!--        <h2 class="especialidades_title">
            Nossos serviços e especialidades
        </h2>
        <div class="especialidades_nomes">
            <ul>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Anestesiologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Cardiologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Cirurgia Geral</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Imagiologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Neurologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Oftalmologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Pediatria</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Psicologia</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Psiquiatria</span></li>
                <li><div class="especialidades_tile"></div><span class="especialidade_nome">Urologia</span></li>
            </ul>
        </div>
        <div class="especialidades_detalhes">
            <h2 class="especialidade_detalhes_title">Um grande número de especialidades para lhe dar o melhor serviço, a sua medida</h2>
            <p>A clínica da idade é dotada de uma equipa de profissionais espalhados por várias especialidades, para que seja dado aos nossos clientes todos e os melhores serviços hospitalares.</p>
            <p>Com o melhor equipamento, pode contar com a melhor satisfação na escolha da nossa clínica, saia melhor de saúde e com um sorriso na sua cara.</p>
            <figure class="especialidade_detalhes_imagem">
                <img src="<?php echo ROOT; ?>img/doctors.png"/>
            </figure>
        </div>-->

    </article>
</section>