<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <link rel="stylesheet" href="css/style.css">

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <script src="js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header class="header">
      <div class="site_center">
      <figure>
          <img class="header_logo" src="<?php echo ROOT; ?>img/big_logo.png" />
      </figure>
          <nav class="header_menu">
              <ul>
                  <li><div class="header_menu_names">início</div><div class="header_menu_barra"></div></li>
                  <li><div class="header_menu_names header_big_menu_link">serviços clínicos</div><div class="header_menu_barra"></div></li>
                  <li><div class="header_menu_names">institucional</div><div class="header_menu_barra"></div></li>
                  <li><div class="header_menu_names">apoio ao cliente</div><div class="header_menu_barra"></div></li>
              </ul>
          </nav>
            <div class="header_big_menu"></div>
      </div>
  </header>

  <div class="site_center">
  <article class="big_banner">
    <h1 class="big_banner_title">
        O melhor para si <br />e para os seus familiaressadasdasda
    </h1>
    <figure class="big_banner_img">
        <img src="<?php echo ROOT;?>img/velhos.png"/>
    </figure>
</article>
  
  